---
title: "on the meaning of fancy, imagination, fantasy, humor, and more"
author: "Olgert Denas"
date: "2013-02-23"
categories: [books, poe, excerpt]
---

I’m getting into Poe lately

excerpts from [here](http://www.eapoe.org/works/criticsm/bj45wn01.htm)

...  — “Fancy combines — Imagination creates.” This was intended, and
has been received, as a distinction; but it is a distinction without a
difference — without even a difference of degree. The Fancy as nearly
creates as the imagination, and neither at all. Novel conceptions are
merely unusual combinations. The mind of man can imagine nothing which
does not exist: — if it could, it would create not only ideally, but
substantially — as do the thoughts of God.

[...]

The fact seems to be that Imagination, Fancy, Fantasy, and humor, have
in common the elements, Combination, and Novelty.

[...]

Fantasy seeks not merely disproportionate but incongruous or
antagonistical elements, the effect is rendered more pleasurable from
its greater positiveness; — there is a merry effort of Truth to shake
from her that which is no property of hers; — and we laugh outright in
recognizing Humor.

[...]

but when either Fancy or Humor is expressed to gain an end — is
pointed at a purpose — whenever either becomes objective in place of
subjective — then it he comes, also, pure Wit or Sarcasm, just as the
purpose is well-intentioned or malevolent.