---
title: "Uno, nessuno, e centomilla"
author: "Olgert Denas"
date: "2013-12-26"
categories: [books, pirandello, excerpt]
---
Yet another excerpt from Pirandello. This is from his “uno, nessuno e centomila”

Mi guardai allo specchio dell’armadio con irresistibile confidenza, fino a strizzare un occhio per significare a quel Moscarda là che noi due intanto c’intendevamo a meraviglia. E anche lui, per dire la verità, subito mi struzzo l’occhio, a confermare l’intesa. (Voi dirette, lo so, che questo dipendeva perché quel Moscarda là nello specchio ero io; e ancora una volta dimostrerete di non aver capito niente. Non ero io, ve lo posso assicurare. Tant’è vero che un istante dopo, prima d’uscire, appena voltai un po’ la testa per riguardarlo in quello specchio, era già un altro, anche per me, con un sorriso diabolico negli occhi azzurri e lucidissimi. Voi ve ne sareste spaventati; io no; perché già lo sapevo; e lo salutai con la mano. Mi saluto con la mano anche lui, per dire la verità.)