name: Update Treadmill Report
on:
  push:
    paths:
      - 'blog/posts/2026-01-03-interval-train/data/*.CSV'  # Only run if a new CSV is added to the data folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python Libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Render Report
        run: quarto render report.qmd

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs # Where Quarto puts the output