---
title: "Adriano Meis e la signorina Adriana"
author: "Olgert Denas"
date: "2013-02-23"
categories: [books, pirandello, excerpt]
---

Se ne offese. Chino’ gli occhi e si strinse un po’ il labbro tra i denti. Per farle piacere, allora, le parlai anch’io con gravita’.

“E… Scusi, signorina: non ci sono bambini, e’ vero, in casa?”

Scosse il capo senza aprir bocca. Forse nella mia domanda senti’ un sapor d’ironia, ch’io pero’ non avevo voluto metterci. Avevo detto bambini e non bambine. Mi affrettai a riparare un altra volta:

“E… dica, signorina: loro non affittano altre camere, e’ vero?”.

“Questa e’ la migliore” mi rispose, senza guardarmi. “Se non le accomoda…”

“No no … Domandavo per sapere se …”

“Ne affitiamo un altra” disse allora ella, alzando gli occhi con aria d’indifferenza forzata. “Di la, posta sula davanti… su la via. E’ occupata da una signorina cha sta con noi ormai da due anni: da’ lezioni di pianoforte… non in casa.”

Accenno’, cosi’ dicendo, un sorriso lieve lieve, e mesto.

Aggiunse:

“Siamo io, il babbo e mio cognato…”

“Paleari?”

“No: Paleari e’ il babbo; mio cognato si chiama Terenzio Papiano. Deve pero’ andar via, col fratello che per ora sta anche lui qua con noi. Mia sorella e’ morta… da sei mesi.”

Per cangiar discorso, le domandai che pigione avrei dovuto pagare; ci accordammo subito; le domandai anche se bisognava lasciare la caparra.

“Faccia lei” mi rispose. “Se vuole piuttosto lasciare il nome…”

Mi tastai in petto, sorridendo nervosamente, e dissi:

“Non ho…. non neppure un biglietto da visita… Mi chiamo Adriano, si’ appunto: ho sentito che si chiama Adriana anche lei, signorina. Forse le fara’ dispiacere…”

“Ma no! Perche’?” fece lei, notando evidentemente il mio curioso imbarazzo e ridendo questa volta come un vera bambina.

Risi anch’io e soggiunsi:

“E allora, se non le dispiace mi chiamo Adriano Meis: ecco fatto! Potrei alloggiare qua stasera stessa? O tornero’ meglio domattina…”

Ella mi rispose: “Come vuole”, ma io me ne andai con l’impressione che le avrei fatto un gran piacere se non fossi piu’ tornato. Avevo osato nentemeno di non tenere nella debita considerazione quella sua veste da camera.