---
title: "Letter 5 (excerpt)"
author: "Olgert Denas"
date: "2015-03-26"
categories: [books, renier maria rilke, excerpt]
---
"In addition, Rome (if one has not yet been acquainted with it) makes one feel stifled with sadness for the first few days: through the gloomy and lifeless museum-atmosphere that it exhales, through the abundance of its pasts, which are brought forth and laboriously held up (pasts on which a tiny present subsists), through the terrible overvaluing, sustained by scholars and philologists and imitated by the ordinary tourist in Italy, of all these disfigured and decaying Things, which, after all, are essentially nothing more than than accidental remains from another time and from another life that is not and should not be ours. Finally, after weeks of daily resistance, one finds oneself somewhat composed again, even though still a bit confused, and one says to oneself: No, there is not more beauty here than in other places, and all these objects that have been marveled at by  generation after generation, mended and restored by the hands of workmen, mean nothing, are nothing, and have no heart and no value; — but there is much beauty here, because everywhere there is much beauty. Waters infinitely full of life move along the ancient aqueducts into the great city and dance in the many city squares over white basins of stone and spread out in large, spacious pools and murmur by day and lift up the murmuring to the night, which is vast here and starry and soft with winds. And there are gardens here, unforgettable boulevards, and staircases designed by Michelangelo, staircases constructed on the pattern of downward-gliding waters and, as they descend, widely giving birth to step out of step as if it were wave out of wave. Through such impressions one gathers oneself, wins oneself back from the exacting multiplicity, which speaks and chatters there (and how talkative it is!), and one slowly learns to recognize very few Things in which something eternal endures that one can love and something solitary that one can gently take part in.”