---
title: "Obama, Snowden, NSA, etc. A speculation"
author: "Olgert Denas"
date: "2013-08-09"
categories: [speculation]
draft: true
---

News on NSA practices on personal data teach us that NSA and the government are archiving information usable against anyone at will, including people that want change. This, happening under the current administration caught some people I know, supporters of president Obama, by surprise. I speculate that the scandals and the whistle-blowing are orchestrated by (part of) the administration in an effort to open (make transparent) the government. Two supporting ideas for this.

The NSA practices, which have probably been going on for years, were uncovered right after the president got elected. This is the best period to achieve what he thinks right and not what is popular.

The people in the government that want an open government, if any, are probably a minority. Causing these scandals is probably the most efficient way.

I know, I know the idea is not solid given the reaction of the government to the whistle-blowers etc.; that is why I call it speculating. What do you think?