---
title: "Fantasy’s buondaries (Pirandello’s reply to critics)"
author: "Olgert Denas"
date: "2013-08-27"
categories: [books, pirandello, excerpt, mattia pascal]
---
My last post on Pirandello’s “The late Mattia Pascal” is an excerpt from his reply to the criticism that the book was fantastic and far from life – real life. Alas, all of the pleasure of reading the reply in Italian will be lost as I try to translate it.

“… Real life has the priceless privilege that despite the multitude of its absurdities, small and big, it doesn’t have to look real. Art, on the other hand, feels a strong need to look real. [According to critics.]

The absurdities of life have no need to look real, because they are real. On the contrary, to be credible, the absurdities of art, need to look real. But then, looking real, they are not  absurdities any more.

A real life event can be absurd; art, to be [real] art, cannot.

If follows that lacking absurdity and fantastic, in the name of reality, art is a banality.

Banality in the name of art, not in the name of life. “


