---
title: "Is Kill Bill a feminist movie?"
author: "Olgert Denas"
date: "2012-10-13"
categories: [movie]
---
Ihave seen only pieces of the movie, one scene in particular made me notice the huge war of sexes with a clear winner: female.

One example is scene where The Bride (Uma Thurman) is about to fight the aides of O-Ren Ishii (Lucy Liu) and others. Just before the slaughter starts, O-Ren Ishii tells the owner of the club to run away (because things are about to get dirty). The guy shits his pants and runs away. What about his wife standing next to him? She remains. It seems like a stupid detail, but it got me thinking and I came up with the following interpretation: the owner of the restaurant, a servile coward man, cannot stand the cruelty of what is about to happen, but his wife can. Just minutes ago, the wife would call him to stand for his honor in front of absurd requests of O-Ren Ishii and her gang.

These parallelisms go on and on: minutes before the slaughter, O-Ren Ishii humiliates a man sitting in their table; At the same night, The Bride is about to kill hundreds of young Japanese man …

It kind of makes sense in broader terms too. There are three male types (i) bad guys samurai soldiers on suits and ties whose limbs are being chopped off like cattle and are being humiliated by a blonde american girl in their very own weapon: the sword. (ii) kung fu masters and sword makers and the like who are amazed by the super-abilities and determination of The Bride and swear fidelity and eternal friendship to her. (iii) Bill, a rat capable of very low actions betrayal etc. On the other hand, there is only one female type (some are good some bad, it doesn’t matter): badass females. When they kill, it is for high motivations or to defend their honor in such a masculine society.