---
title: "Papiano secondo Adriano Meis"
author: "Olgert Denas"
date: "2013-08-22"
categories: [books, pirandello, excerpt]
---
Aveva quarant’anni, Papiano, ed era alto di statura e robusto di membra: un po’ calvo, con un grosso pajo di baffi brizzolati appena appena sotto il naso, un bel nasone dalle narici frementi; occhi grigi, acuti e irrequieti come le mani. Vedeva tutto e toccava tutto. Mentre, per esempio, stava a parlar con me, s’accorgeva – non so come – che Adriana, dietro a lui, stentava a pulire e a rimettere a posto qualche oggetto nella camera, e subito, assaettandosi:

“Pardon!”

Correva a lei, le toglieva l’oggetto dalle mani:

“No figliuola mia, guarda, si fa cosi’!”.

E lo ripuliva lui, lo rimetteva a posto lui, e tornava a me. Oppure s’accorgeva che il fratello, il quale soffriva di convulsioni epilettiche, “s’incantava”, e correva a dargli schiaffetti su le guance, biscottini sul naso:

“Scipione! Scipione!”.

O gli soffiava in faccia, fino a farlo rivenire.

Chi sa quanto mi ci sarei divertito, se non avessi avuto quella maledetta coda di paglia!

Certo egli se ne accorse fin dai primi giorni, o – per lo meno – me la intravide.
